# Generated by Django 3.1.5 on 2021-01-20 19:16

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210118_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='django.jpg', upload_to=blog.models.user_directory_path, verbose_name='Image'),
        ),
    ]
